# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
    # Enable version updates for npm
    - package-ecosystem: 'npm'
      # Look for `package.json` and `lock` files in the root directory
      directory: '/'
      # Check the npm registry for updates every week
      schedule:
          interval: 'weekly'
      # Ignore major version updates
      ignore:
          - dependency-name: '*'
            update-types: ['version-update:semver-major']
      # Raise all npm pull requests with assignees
      assignees:
          - 'melbos'

    # Enable version updates for composer
    - package-ecosystem: 'composer'
      # Look for `composer.json` and `composer.lock` files in the root directory
      directory: '/'
      # Check for updates every week
      schedule:
          interval: 'weekly'
      # Raise all composer pull requests with assignees
      assignees:
          - 'melbos'
